
import "./globals.css";
import { Header } from "@/components/Header/Header";
import { Poppins } from 'next/font/google'





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700'] })
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`background ${poppins.className}`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
