
import "./globals.css";
import { Header } from "@/components/Header/Header";





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`  bg-gradient-to-b from-yellow-100 via-pink-100 to-blue-100 min-h-screen ` }
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
